import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { ThemeProvider } from "@/component/ui/themeprovider"
import { auth } from "@clerk/nextjs/server";
import { SyncActiveOrganization } from "./components/SyncActiveOrganization";

import GoogleMapsScript from './components/GoogleMapsScriptComponent';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
 };
// const apiKey = 'AIzaSyCGsFQ4w-sqBF-lwF_WwCdvGny2oiWUjTg';
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId, sessionClaims } = auth();
  return (
  <ClerkProvider>
     {/* <LoadScript googleMapsApiKey={apiKey} libraries={['places']}> */}
    <SyncActiveOrganization membership={sessionClaims?.membership } />

    <html lang="en">
    {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          ></ThemeProvider>  */}
      <body className={inter.className }> {children}  <GoogleMapsScript /> </body>
    </html>
    {/* </LoadScript> */}
    </ClerkProvider>
  );
}
